app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
    
    Route::controllers([
            'auth' => 'Auth\AuthController',
            'password' => 'Auth\PasswordController',
    ]);
    Route::get('/',function(){
        return redirect()->route('addressbook.index');
        
    });
//    Route::get('home',function(){
//        return redirect()->route('addressbook.index');
//        
//    });
    Route::group(['middleware' => ['auth']], function() {
        Route::resource('addressbook','AdressBookController');
        Route::resource('profile','ProfileController');
    });

app/User.php
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'email', 'password'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

}

app/models/address.php
<?php namespace App\models;

use Illuminate\Database\Eloquent\Model;

class address extends Model {

	

}

app/Http/Controllers/AdressBookController.php
<?php namespace App\Http\Controllers;
use App\Model\Address;
use Illuminate\Http\Request;

class AdressBookController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Home Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders your application's "dashboard" for users that
	| are authenticated. Of course, you are free to change or remove the
	| controller as you wish. It is just here to get your app started!
	|
	*/  

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
	}

	/**
	 * Show the application dashboard to the user.
	 *
	 * @return Response
	 */
	public function index() 
	{
            return view('address_book.index');
	}
	public function create() 
	{
            return view('address_book.add');
	}
	public function store(Request $request) 
	{
            
            echo '<pre>';
            print_r($request->all());
            echo '</pre>';
            exit();
            $rules[] = '';
            $rules['address_book_title'] ='required' ;
            $rules['contact_person_name'] ='required' ;
            $rules['contact_person_number'] ='required' ;
            $rules['address_line_1'] ='required' ;
            $rules['address_line_2'] ='required' ;
            $rules['address_line_3'] ='required' ;
            $rules['pin_code'] ='required' ;
            $rules['city'] ='required' ;
            $rules['state'] ='required' ;
            $rules['country'] ='required' ;
            $messages = [''];
            $validator = \Validator::make($request->all(),$rules);
            if($validator->fails()){
                return redirect()->back()->withInput()->withErrors($validator);
            }

            $address = new Address();
            $address->fill($request->all());
            $addressSave = $address->save();
            if($addressSave){
                return redirect()->route('addressbook.index');
            } else {
                return redirect()->back()->withInput()->withErrors(array('error' => 'Couldn\'t add new address. Please try again'));
            }
	}
        

}

app/Http/Controllers/Controller.php
<?php namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesCommands;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends BaseController {

	use DispatchesCommands, ValidatesRequests;

}

app/Http/Controllers/ProfileController.php
<?php namespace App\Http\Controllers;

class ProfileController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Welcome Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders the "marketing page" for the application and
	| is configured to only allow guests. Like most of the other sample
	| controllers, you are free to modify or remove it as you desire.
	|
	*/

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
            
	}

	/**
	 * Show the application welcome screen to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('profile');
	}

}

resources/views/address_book.blade.php
@extends('app')

@section('content')

  <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <form class="form-horizontal" role="form" action="/product/create" method="POST">
                        <div class="form-group">
                            <label for="address_book_title" class="col-sm-2 control-label">Address Book Title</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="address_book_title" placeholder="Address Book Title" name="address_book_title">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_person_name" class="col-sm-2 control-label">Contact Person Name</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="contact_person_name" placeholder="Contact Person Name" name="contact_person_name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_person_name" class="col-sm-2 control-label">Contact Person Number</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="contact_person_number" placeholder="Contact Person Number" name="contact_person_number">
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="address_line_1" class="col-sm-2 control-label">Address Line 1</label>
                            <div class="col-sm-6">
                                <textarea class="form-control" id="address_line_1" placeholder="address line 1" rows="5"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address_line_2" class="col-sm-2 control-label">Address Line 2</label>
                            <div class="col-sm-6">
                                <textarea class="form-control" id="address_line_2" placeholder="address line 2" rows="5"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address_line_3" class="col-sm-2 control-label">Address Line 3</label>
                            <div class="col-sm-6">
                                <textarea class="form-control" id="address_line_3" placeholder="address line 3" rows="5"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="pin_code" class="col-sm-2 control-label">Pin Code</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="pin_code" placeholder="Pin Code" name="pin_code">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="city" class="col-sm-2 control-label">City</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="city" placeholder="City" name="city">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="state" class="col-sm-2 control-label">State</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="state" placeholder="State" name="state">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="country" class="col-sm-2 control-label">Country</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="country" placeholder="Country" name="country">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
@endsection

resources/views/address_book/add.blade.php
@extends('app')

@section('content')

  <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <form class="form-horizontal" role="form" action="{{route('addressbook.store')}}" method="POST">
                        <div class="form-group">
                            <label for="address_book_title" class="col-sm-2 control-label">Address Book Title</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="address_book_title" placeholder="Address Book Title" name="address_book_title">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_person_name" class="col-sm-2 control-label">Contact Person Name</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="contact_person_name" placeholder="Contact Person Name" name="contact_person_name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_person_name" class="col-sm-2 control-label">Contact Person Number</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="contact_person_number" placeholder="Contact Person Number" name="contact_person_number">
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="address_line_1" class="col-sm-2 control-label">Address Line 1</label>
                            <div class="col-sm-6">
                                <textarea class="form-control" id="address_line_1" placeholder="address line 1" rows="5" name="address_line_1"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address_line_2" class="col-sm-2 control-label">Address Line 2</label>
                            <div class="col-sm-6">
                                <textarea class="form-control" id="address_line_2" placeholder="address line 2" rows="5" name="address_line_2"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address_line_3" class="col-sm-2 control-label">Address Line 3</label>
                            <div class="col-sm-6">
                                <textarea class="form-control" id="address_line_3" placeholder="address line 3" rows="5" name="address_line_3"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="pin_code" class="col-sm-2 control-label">Pin Code</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="pin_code" placeholder="Pin Code" name="pin_code">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="city" class="col-sm-2 control-label">City</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="city" placeholder="City" name="city">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="state" class="col-sm-2 control-label">State</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="state" placeholder="State" name="state">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="country" class="col-sm-2 control-label">Country</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="country" placeholder="Country" name="country">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
@endsection

resources/views/address_book/edit.blade.php
@extends('app')

@section('content')

  <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <form class="form-horizontal" role="form" action="/product/create" method="POST">
                        <div class="form-group">
                            <label for="address_book_title" class="col-sm-2 control-label">Address Book Title</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="address_book_title" placeholder="Address Book Title" name="address_book_title">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_person_name" class="col-sm-2 control-label">Contact Person Name</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="contact_person_name" placeholder="Contact Person Name" name="contact_person_name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_person_name" class="col-sm-2 control-label">Contact Person Number</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="contact_person_number" placeholder="Contact Person Number" name="contact_person_number">
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="address_line_1" class="col-sm-2 control-label">Address Line 1</label>
                            <div class="col-sm-6">
                                <textarea class="form-control" id="address_line_1" placeholder="address line 1" rows="5"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address_line_2" class="col-sm-2 control-label">Address Line 2</label>
                            <div class="col-sm-6">
                                <textarea class="form-control" id="address_line_2" placeholder="address line 2" rows="5"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address_line_3" class="col-sm-2 control-label">Address Line 3</label>
                            <div class="col-sm-6">
                                <textarea class="form-control" id="address_line_3" placeholder="address line 3" rows="5"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="pin_code" class="col-sm-2 control-label">Pin Code</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="pin_code" placeholder="Pin Code" name="pin_code">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="city" class="col-sm-2 control-label">City</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="city" placeholder="City" name="city">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="state" class="col-sm-2 control-label">State</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="state" placeholder="State" name="state">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="country" class="col-sm-2 control-label">Country</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" id="country" placeholder="Country" name="country">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
@endsection

resources/views/address_book/index.blade.php
@extends('app')

@section('content')

  <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <a href="{{route('addressbook.create')}}" class="btn btn-info">Add Address</a>
                    
                </div>
            </div>
        </div>
@endsection

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Laravel</title>

	<link href="{{ asset('/css/app.css') }}" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="{{route('addressbook.index')}}" >Manage Address Book</a></li>
					<li><a href="{{route('profile.index')}}" >Manage Profile</a></li>
                                        
                            
                                        
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="{{ url('/auth/login') }}">Login</a></li>
						<li><a href="{{ url('/auth/register') }}">Register</a></li>
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{ url('/auth/logout') }}">Logout</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

	@yield('content')

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12 col-md-offset-1">
                            <a href="{{route('profile.index')}}" class="btn btn-lg btn-primary">Manage Profile</a>
                            <a href="{{route('addressbook.index')}}" class="btn btn-lg btn-success">Manage Address Book</a>
		</div>
	</div>
</div>
@endsection

resources/views/profile.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12 col-md-offset-1">
                    hi m profile
		</div>
	</div>
</div>
@endsection